### ISSUE TITLE
Feature: Feature "attributes"

### ISSUE THREAD

**Issue by taqtiqa-mark** [tikv/minitrace-rust#140]
To support this use case: The minitrace-attributes crate is a dependency only in development:

```toml
[package]
...
resolver = "2"

[dependencies]
minitrace = {version = "0.5", default-features = false}

[dev-dependencies]
minitrace = {version = "0.5", features = ["attributes"]}
```
